services:
  - type: web
    name: sales-backend
    env: docker
    rootDir: backend
    plan: free
    autoDeploy: true

  - type: web
    name: sales-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run preview --host 0.0.0.0 --port 10000
    plan: free
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        fromService:
          name: sales-backend
          type: web
          property: hostport
